=== TZP001/test/B21/win_b64/reffiles/lmsfddxml/LMSFddConfiguration.dtd
<!ELEMENT LMSFddDisplayConfiguration (LMSFddScaleDescriptor*, LMSFddLimitCalcDescriptor*, LMSFddLimitTypeDescriptor*, LMSFddTransformationDescriptor*, LMSFddWeightingDescriptor*, LMSFddLimitDescriptor*, LMSFddDofTypeDescriptor*, LMSFddDofUsageDescriptor*, 
                                      LMSFddDofRoleDescriptor*, LMSFddSpaceTypeDescriptor*, LMSFddSpaceDescriptor*, 
                                      LMSFddCursorPartDescriptor*, LMSFddCursorDescriptor*, LMSFddCursorInputValueDescriptor*, LMSFddCursorTypeDescriptor*, LMSFddCursorDefinitionDescriptor*,
                                      LMSFddDirectionDescriptor*, LMSFddDrawTypeDescriptor*, LMSFddDirectionSystemDescriptor*, LMSFddGraphAxisDescriptor*, LMSFddSPSDescriptor*, LMSFddGraphDescriptor*) >
<!ELEMENT LMSFddSpaceTypeDescriptor EMPTY>
<!ELEMENT LMSFddDofRoleDescriptor EMPTY>
<!ELEMENT LMSFddDofUsageDescriptor EMPTY>
<!ELEMENT LMSFddScaleDescriptor EMPTY>
<!ELEMENT LMSFddLimitTypeDescriptor EMPTY>
<!ELEMENT LMSFddTransformationDescriptor EMPTY>
<!ELEMENT LMSFddLimitDescriptor EMPTY>
<!ELEMENT LMSFddDofTypeDescriptor (LMSFddFormatDescriptor*) >
<!ELEMENT LMSFddOptionDependentDofUsage EMPTY >
<!ELEMENT LMSFddFormatDescriptor EMPTY>
<!ELEMENT LMSFddDofDescriptor (LMSFddOptionDependentDofUsage+)>
<!ELEMENT LMSFddSpaceOption EMPTY>
<!ELEMENT LMSFddLimitCalcDescriptor EMPTY>
<!ELEMENT LMSFddSpaceDescriptor (LMSFddSpaceOption+,LMSFddDofDescriptor+) >

<!ELEMENT LMSFddCursorPartDescriptor EMPTY>
<!ELEMENT LMSFddCursorDescriptor EMPTY>
<!ELEMENT LMSFddCursorInputValueDescriptor EMPTY>
<!ELEMENT LMSFddCursorTypeDescriptor EMPTY>
<!ELEMENT LMSFddCursorDefinitionPartDescriptor EMPTY>
<!ELEMENT LMSFddCursorDefinitionDescriptor (LMSFddCursorDefinitionPartDescriptor+)>

<!ELEMENT LMSFddDirectionDescriptor EMPTY>
<!ELEMENT LMSFddDrawTypeDescriptor EMPTY>
<!ELEMENT LMSFddDirectionSystemDescriptor EMPTY>
<!ELEMENT LMSFddSPSDescriptor (LMSFddDDToGraphAxisMap+)>
<!ELEMENT LMSFddDDToGraphAxisMap EMPTY>
<!ELEMENT LMSFddGraphAxisDescriptor EMPTY>
<!ELEMENT LMSFddWeightingDescriptor EMPTY>

<!ELEMENT LMSFddGraphAreaDescriptor EMPTY>
<!ELEMENT LMSFddPlotDescriptor EMPTY>
<!ELEMENT LMSFddGraphDescriptor (LMSFddGraphAreaDescriptor+, LMSFddPlotDescriptor)>

<!ATTLIST LMSFddSpaceTypeDescriptor id ID #REQUIRED
                                    res IDREFS #REQUIRED
                                    args IDREFS #REQUIRED>

<!ATTLIST LMSFddDofRoleDescriptor id ID #REQUIRED>

<!ATTLIST LMSFddWeightingDescriptor id ID #REQUIRED>

<!ATTLIST LMSFddDirectionDescriptor id ID #REQUIRED>

<!ATTLIST LMSFddDrawTypeDescriptor id ID #REQUIRED>

<!ATTLIST LMSFddDirectionSystemDescriptor id ID #REQUIRED
																					dirs IDREFS #REQUIRED
                                          dt   IDREF #REQUIRED>

<!ATTLIST LMSFddGraphAxisDescriptor id ID #REQUIRED
																		direction IDREF #REQUIRED>

<!ATTLIST LMSFddSPSDescriptor id ID #REQUIRED
                              graphaxes IDREFS #REQUIRED>

<!ATTLIST LMSFddDDToGraphAxisMap id ID #REQUIRED
																 dd IDREFS #REQUIRED
																 space IDREF #REQUIRED>



<!ATTLIST LMSFddDofUsageDescriptor id ID #REQUIRED
                                   doftype IDREF #REQUIRED
                                   limits IDREFS #REQUIRED
                                   defaultlimitcalc CDATA #REQUIRED>
<!ATTLIST LMSFddLimitCalcDescriptor id ID           #REQUIRED
                                    limitname CDATA #REQUIRED>
<!ATTLIST LMSFddScaleDescriptor id ID #REQUIRED>
<!ATTLIST LMSFddLimitTypeDescriptor id ID #REQUIRED>
<!ATTLIST LMSFddLimitDescriptor id ID #REQUIRED
                                limittype IDREF #REQUIRED>
<!ATTLIST LMSFddDofTypeDescriptor id ID #REQUIRED
                                  type (Cont|Discrete) #REQUIRED
                                  includeweighting (yes|no) #REQUIRED                                 
                                   calctypes IDREFS #REQUIRED>

<!ATTLIST LMSFddSpaceOption id ID #REQUIRED>
<!ATTLIST LMSFddSpaceDescriptor id ID #REQUIRED
                                spacetype IDREF #REQUIRED
                                latetype CDATA #REQUIRED>
<!ATTLIST LMSFddDofDescriptor id ID #REQUIRED
                                   role IDREF #REQUIRED>
<!ATTLIST LMSFddFormatDescriptor id ID #REQUIRED
                                 scale IDREF #REQUIRED
                                 limittype IDREF #REQUIRED
                                 transform IDREF #REQUIRED>
<!ATTLIST LMSFddTransformationDescriptor id ID #REQUIRED
                                         latetype CDATA #REQUIRED>
<!ATTLIST LMSFddOptionDependentDofUsage dofusage IDREF #REQUIRED
                              spaceoption IDREF #REQUIRED
                              showunit (yes|no) #REQUIRED>


<!ATTLIST LMSFddCursorPartDescriptor id ID #REQUIRED>
<!ATTLIST LMSFddCursorDescriptor id ID #REQUIRED
                                 parts IDREFS #REQUIRED>
<!ATTLIST LMSFddCursorInputValueDescriptor id ID #REQUIRED
                                           fordofusage IDREF #REQUIRED>

<!ATTLIST LMSFddCursorTypeDescriptor id ID #REQUIRED
                                     inputvalues IDREFS #REQUIRED>
<!ATTLIST LMSFddCursorDefinitionDescriptor id ID #REQUIRED
                                           cursor IDREF #REQUIRED
                                           snaptodata (yes|no) #REQUIRED>
<!ATTLIST LMSFddCursorDefinitionPartDescriptor id ID #REQUIRED
                                           type IDREF #REQUIRED
                                           forcursorpart IDREF #REQUIRED>


<!ATTLIST LMSFddGraphAreaDescriptor id ID #REQUIRED
																		sps IDREF #REQUIRED
																		directionsystem IDREF #REQUIRED
                                    includegraphtitle (yes|no) #REQUIRED>


<!ATTLIST LMSFddPlotDescriptor id ID #REQUIRED
															 latetype CDATA #REQUIRED
															 graphareas IDREFS #REQUIRED>

<!ATTLIST LMSFddGraphDescriptor id ID #REQUIRED
                                space IDREF #REQUIRED
																nbplots (ZeroOrOne|ZeroOrMore) #REQUIRED
                                supportedcursors IDREFS #IMPLIED
                                src              CDATA #IMPLIED>

=== TZP001/test/B21/win_b64/reffiles/lmsfddxml/LMSFddConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="LMSFddConfiguration.xsl"?>
<!DOCTYPE LMSFddDisplayConfiguration SYSTEM "LMSFddConfiguration.dtd" []>

<!-- This file can be viewed as an illustrated catalog when using Internet Explorer 6 or Mozilla -->

<LMSFddDisplayConfiguration>
  
  <LMSFddScaleDescriptor id="Log"/>
  <LMSFddScaleDescriptor id="Oct"/>
  <LMSFddScaleDescriptor id="Power2"/>
  <LMSFddScaleDescriptor id="Lin"/>
  <LMSFddScaleDescriptor id="PhaseUnWrappedDegrees"/>
  <LMSFddScaleDescriptor id="PhaseUnWrappedRadians"/>
  <LMSFddScaleDescriptor id="dB"/>

  <LMSFddLimitCalcDescriptor id="FreeLimits" limitname="None"/>
  <LMSFddLimitCalcDescriptor id="OptimizedLimits" limitname="None"/>
  <LMSFddLimitCalcDescriptor id="ADLimits" limitname="ApplicationDefined"/>
  <LMSFddLimitCalcDescriptor id="AbsoluteLimits" limitname="None"/>
  <LMSFddLimitCalcDescriptor id="FixedLimits" limitname="Fixed"/>

  <LMSFddLimitTypeDescriptor id="dBLimitType"/>
  <LMSFddLimitTypeDescriptor id="PhaseLimitType" />
  <LMSFddLimitTypeDescriptor id="AmplitudeLimitType"/>
  <LMSFddLimitTypeDescriptor id="RealLimitType"/>
  <LMSFddLimitTypeDescriptor id="ImagLimitType"/>
  <LMSFddLimitTypeDescriptor id="ContLimitType"/>

  <LMSFddTransformationDescriptor id="dBTransform" latetype = "LMSFdddBTransform"/>
  <LMSFddTransformationDescriptor id="dBRMSTransform" latetype = "LMSFdddBRMSTransform"/>
  <LMSFddTransformationDescriptor id="AmplitudeTransform" latetype = "LMSFddAmplitudeTransform"/>
  <LMSFddTransformationDescriptor id="RealTransform" latetype = "LMSFddRealTransform"/>
  <LMSFddTransformationDescriptor id="ImagTransform" latetype = "LMSFddImagTransform"/>
  <LMSFddTransformationDescriptor id="PhaseTransform" latetype = "LMSFddPhaseTransform"/>
  <LMSFddTransformationDescriptor id="NoTransformContinuous" latetype = "LMSFddNoTransformContinuous"/>

  <LMSFddWeightingDescriptor id="NoWeighting"/>
  <LMSFddWeightingDescriptor id="AWeighting"/>
  <LMSFddWeightingDescriptor id="BWeighting"/>
  <LMSFddWeightingDescriptor id="CWeighting"/>
  <LMSFddWeightingDescriptor id="DWeighting"/>

  <LMSFddLimitDescriptor id="AmplitudeLimit" limittype="AmplitudeLimitType"/>
  <LMSFddLimitDescriptor id="dBLimit" limittype="dBLimitType"/>
  <LMSFddLimitDescriptor id="RealLimit" limittype="RealLimitType"/>
  <LMSFddLimitDescriptor id="ImagLimit" limittype="ImagLimitType"/>
  <LMSFddLimitDescriptor id="PhaseLimit" limittype="PhaseLimitType"/>
  <LMSFddLimitDescriptor id="ContArg1Limit" limittype="ContLimitType"/>
  <LMSFddLimitDescriptor id="ContArg2Limit" limittype="ContLimitType"/>

  <LMSFddDofTypeDescriptor id="SimpleAmplitudeResDofType" type = "Cont" includeweighting="no" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="SimpleAmplitudeResFormat" transform="NoTransformContinuous" scale="Lin" limittype="AmplitudeLimit"/>   
    <LMSFddFormatDescriptor id="SimpleAmplitudeResLogFormat" transform="NoTransformContinuous" scale="Log" limittype="AmplitudeLimit"/>
  </LMSFddDofTypeDescriptor>

  <LMSFddDofTypeDescriptor id="AmplitudeResDofType" type = "Cont" includeweighting="yes" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="AmplitudeResFormat" transform="NoTransformContinuous" scale="Lin" limittype="AmplitudeLimit"/>   
    <LMSFddFormatDescriptor id="AmplitudeResLogFormat" transform="NoTransformContinuous" scale="Log" limittype="AmplitudeLimit"/>
    <LMSFddFormatDescriptor id="AmplitudeResdBRMSFormat" transform="dBRMSTransform" scale="dB" limittype="dBLimit"/>
    <LMSFddFormatDescriptor id="AmplitudeResdBFormat" transform="dBTransform" scale="dB" limittype="dBLimit"/>
  </LMSFddDofTypeDescriptor>

  <LMSFddDofTypeDescriptor id="RealResDofType" type = "Cont" includeweighting="yes" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="RealResRealFormat" transform="NoTransformContinuous" scale="Lin" limittype="RealLimitType"/>
  </LMSFddDofTypeDescriptor>

  <LMSFddDofTypeDescriptor id="ImagResDofType" type = "Cont" includeweighting="yes" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="ImagResImagFormat" transform="NoTransformContinuous" scale="Lin" limittype="ImagLimitType"/>
  </LMSFddDofTypeDescriptor>

  <LMSFddDofTypeDescriptor id="PhaseResDofType" type = "Cont" includeweighting="yes" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="PhaseResPhaseUnwrappedDegreesFormat" transform="NoTransformContinuous" scale="PhaseUnWrappedDegrees" limittype="PhaseLimitType"/>
    <LMSFddFormatDescriptor id="PhaseResPhaseUnwrappedRadiansFormat" transform="NoTransformContinuous" scale="PhaseUnWrappedRadians" limittype="PhaseLimitType"/>
  </LMSFddDofTypeDescriptor>

  <LMSFddDofTypeDescriptor id="ComplexResDofType" type = "Cont" includeweighting="yes" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="ComplexResRealFormat" transform="RealTransform" scale="Lin" limittype="RealLimitType"/>
    <LMSFddFormatDescriptor id="ComplexResImagFormat" transform="ImagTransform" scale="Lin" limittype="ImagLimitType"/>
    <LMSFddFormatDescriptor id="ComplexResPhaseUnwrappedDegreesFormat" transform="PhaseTransform" scale="PhaseUnWrappedDegrees" limittype="PhaseLimitType"/>
    <LMSFddFormatDescriptor id="ComplexResPhaseUnwrappedRadiansFormat" transform="PhaseTransform" scale="PhaseUnWrappedRadians" limittype="PhaseLimitType"/>
    <LMSFddFormatDescriptor id="ComplexResAmplitudeFormat" transform="AmplitudeTransform" scale="Lin" limittype="AmplitudeLimitType"/>  
    <LMSFddFormatDescriptor id="ComplexResLogFormat" transform="AmplitudeTransform" scale="Log" limittype="AmplitudeLimitType"/>              
    <LMSFddFormatDescriptor id="ComplexResdBRMSFormat" transform="dBRMSTransform" scale="dB" limittype="dBLimitType"/>                
    <LMSFddFormatDescriptor id="ComplexResdBFormat" transform="dBTransform" scale="dB" limittype="dBLimitType"/>                
  </LMSFddDofTypeDescriptor>

  <LMSFddDofTypeDescriptor id="ContArgDofType" type = "Cont" includeweighting="no" calctypes="FreeLimits OptimizedLimits FixedLimits ADLimits">
    <LMSFddFormatDescriptor id="ContArgLinFormat" transform="NoTransformContinuous" scale="Lin" limittype="ContLimitType"/>
    <LMSFddFormatDescriptor id="ContArgOctFormat" transform="NoTransformContinuous" scale="Oct" limittype="ContLimitType"/>
    <LMSFddFormatDescriptor id="ContArgDecFormat" transform="NoTransformContinuous" scale="Log" limittype="ContLimitType"/>
    <LMSFddFormatDescriptor id="ContArgPower2Format" transform="NoTransformContinuous" scale="Power2" limittype="ContLimitType"/>
  </LMSFddDofTypeDescriptor>

  <LMSFddDofUsageDescriptor id="SimpleAmplitudeResDofUsage" doftype="SimpleAmplitudeResDofType" limits="AmplitudeLimit" defaultlimitcalc="OptimizedLimits"/>
  <LMSFddDofUsageDescriptor id="AmplitudeResDofUsage" doftype="AmplitudeResDofType" limits="dBLimit AmplitudeLimit" defaultlimitcalc="OptimizedLimits"/>
  <LMSFddDofUsageDescriptor id="RealResDofUsage" doftype="RealResDofType" limits="RealLimit" defaultlimitcalc="OptimizedLimits"/>
  <LMSFddDofUsageDescriptor id="ImagResDofUsage" doftype="ImagResDofType" limits="ImagLimit" defaultlimitcalc="OptimizedLimits"/>
  <LMSFddDofUsageDescriptor id="PhaseResDofUsage" doftype="PhaseResDofType" limits="PhaseLimit" defaultlimitcalc="OptimizedLimits"/>
  <LMSFddDofUsageDescriptor id="ComplexResDofUsage" doftype="ComplexResDofType" limits="dBLimit AmplitudeLimit RealLimit ImagLimit PhaseLimit" defaultlimitcalc="OptimizedLimits"/>
  <LMSFddDofUsageDescriptor id="ContArg1DofUsage" doftype="ContArgDofType" limits="ContArg1Limit" defaultlimitcalc="FreeLimits"/>
  <LMSFddDofUsageDescriptor id="ContArg2DofUsage" doftype="ContArgDofType" limits="ContArg2Limit" defaultlimitcalc="FreeLimits"/>

  <LMSFddDofRoleDescriptor id="Arg1"/>
  <LMSFddDofRoleDescriptor id="Arg2"/>
  <LMSFddDofRoleDescriptor id="Res1"/>
  <LMSFddDofRoleDescriptor id="Res2"/>

  <LMSFddSpaceTypeDescriptor id="Simple2D" args="Arg1" res="Res1"/>
  <LMSFddSpaceTypeDescriptor id="Simple3D" args="Arg1 Arg2" res="Res1"/>
  <LMSFddSpaceTypeDescriptor id="Complex2D" args="Arg1" res="Res1 Res2"/>


  <LMSFddSpaceDescriptor id="SimpleAmplXY" latetype="LMSFddI2DSpaceDescriptor" spacetype="Simple2D">
    <LMSFddSpaceOption id="SimpleAmplXY_OptionXY"/>
    <LMSFddDofDescriptor id="SimpleAmplXY_Arg" role="Arg1">
      <LMSFddOptionDependentDofUsage dofusage="ContArg1DofUsage" spaceoption="SimpleAmplXY_OptionXY" showunit="yes"/>
    </LMSFddDofDescriptor>
    <LMSFddDofDescriptor id="SimpleAmplXY_Res" role="Res1">
      <LMSFddOptionDependentDofUsage dofusage="SimpleAmplitudeResDofUsage" spaceoption="SimpleAmplXY_OptionXY" showunit="yes"/>
    </LMSFddDofDescriptor>
  </LMSFddSpaceDescriptor>

  <LMSFddSpaceDescriptor id="XY" latetype="LMSFddI2DSpaceDescriptor" spacetype="Simple2D">
    <LMSFddSpaceOption id="XY_OptionXY"/>
    <LMSFddDofDescriptor id="XY_Arg" role="Arg1">
      <LMSFddOptionDependentDofUsage dofusage="ContArg1DofUsage" spaceoption="XY_OptionXY" showunit="yes"/>
    </LMSFddDofDescriptor>
    <LMSFddDofDescriptor id="XY_Res" role="Res1">
      <LMSFddOptionDependentDofUsage dofusage="ComplexResDofUsage" spaceoption="XY_OptionXY" showunit="yes"/>
    </LMSFddDofDescriptor>
  </LMSFddSpaceDescriptor>

  <LMSFddSpaceDescriptor id="Colormap" latetype="LMSFddI25DSpaceDescriptor" spacetype="Simple3D">
    <LMSFddSpaceOption id="Colormap_OptionXYZ"/>
    <LMSFddDofDescriptor id="Colormap_Arg1" role="Arg1">
      <LMSFddOptionDependentDofUsage dofusage="ContArg1DofUsage" spaceoption="Colormap_OptionXYZ" showunit="yes"/>
    </LMSFddDofDescriptor>
    <LMSFddDofDescriptor id="Colormap_Arg2" role="Arg2">
      <LMSFddOptionDependentDofUsage dofusage="ContArg2DofUsage" spaceoption="Colormap_OptionXYZ" showunit="yes"/>
