=== TZP001/test/B21/win_b64/reffiles/disciplines/Application.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- COPYRIGHT DASSAULT SYSTEMES 2001 -->
<!-- Sept 2001 creation of this DTD for syntax of application definition in PRM--> 



<!ELEMENT Application (Alias | Resource)* 	 >

<!ATTLIST Application
		Name 	CDATA #REQUIRED
		Description CDATA "No Description"
		Visible (yes | no) "yes"	>


<!ELEMENT Alias EMPTY>

<!ATTLIST Alias
		Name 	 CDATA #REQUIRED
		Value	 CDATA #REQUIRED
>


<!ELEMENT Resource (ID?) 	 >

<!ATTLIST Resource 
    Name 	CDATA										#REQUIRED  										            
	Description CDATA									"No Description" 	 
	Visible (yes | no)									"yes"
>

<!ELEMENT ID EMPTY > 
<!ATTLIST ID 
	Type 	(Catia | Misc | Path)						"Misc"
	Path	    CDATA									"No Description" 
	Location 	CDATA									#REQUIRED 
	Driver 		CDATA									"No Description"
	Access	(R | RW)									"R"				
>

=== TZP001/test/B21/win_b64/reffiles/disciplines/CATElectricalDiagram.xml
<!DOCTYPE Application SYSTEM "Application.dtd">

<Application Name="CATElectricalDiagram" Description="Electrical Diagram Application" Visible = "no">

     <Resource Name="ElectricalDiagramCatalog" Description="Electrical Components Catalog">
           <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\ElectricalDiagrams\ComponentCatalogs\Electrical_ANSI.catalog"/>
     </Resource>

     <Resource Name="ElectricalOnOffSheetCatalog" Description="Electrical OnOffSheet Catalog">
           <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\ElectricalDiagrams\ComponentCatalogs\Electrical_ANSI_OffSheets.catalog"/>
     </Resource>

     <Resource Name="AnnotationBreakCatalog" Description="Electrical Diagram Annotation Break Symbols Catalog">
         <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\ElectricalDiagrams\ComponentCatalogs\Electrical_AnnotationBreaks.catalog"/>
     </Resource>

     <Resource Name="AnnotationSymbolCatalog" Description="Electrical Diagram Annotation Symbols Catalog">
         <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\ElectricalDiagrams\ComponentCatalogs\Electrical_AnnotationSymbols.catalog"/>
     </Resource>

     <Resource Name="ElectricalAnnotationCatalog" Description="Electrical Annotation Catalog">
           <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\SampleData\ElectricalAnnotations.catalog"/>
     </Resource>

     <Resource Name="RulesChecksCatalog" Description="Knowledgeware Rules And Checks Catalog">
         <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\DesignRules\ElectricalDiagramRulesAndChecks.catalog"/>
     </Resource>

     <Resource Name="ElectricalGraphicNames" Description="Electrical Graphic Names">
         <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\SampleData"/>
     </Resource>

     <Resource Name="ElectricalCablesCatalog" Description="Electrical Cables Catalog">
           <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\ElectricalDiagrams\ComponentCatalogs\Electrical_Cables.catalog"/>
     </Resource>

     <Resource Name="ElectricalReportDefinitions" Description="Electrical Report Definitions Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\SampleData"/>
     </Resource>

     <Resource Name="ReportExpressions" Description="Report Expressions Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\ReporterData"/>
     </Resource>

     <!--  Reporter Style Sheet Directory   -->
     <Resource Name="ReportStyleSheet" Description="Report Style Sheet Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\ReporterData"/>
     </Resource>

     <Resource Name="ZonesCatalog" Description="Zones Shared Catalog">
           <ID  Type="Catia" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\Zones\CATMldZone.catalog"/>
     </Resource>

  <!-- ************** ID SCHEMA RESOURCES ************** -->

     <Resource Name="EquipmentIDSchema" Description="Equipment ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Equipment\DataDictionary"/>
     </Resource>

     <Resource Name="PipingIDSchema" Description="Piping ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Piping\DataDictionary"/>
     </Resource>

     <Resource Name="InstrumentIDSchema" Description="Instrument ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Instrument\DataDictionary"/>
     </Resource>

     <Resource Name="HVACIDSchema" Description="HVAC ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\HVAC\DataDictionary"/>
     </Resource>

     <Resource Name="TubingIDSchema" Description="Tubing ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Tubing\DataDictionary"/>
     </Resource>

     <Resource Name="WaveguideIDSchema" Description="Waveguide ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Waveguide\DataDictionary"/>
     </Resource>

     <Resource Name="MultiDisciplineIDSchema" Description="MultiDiscipline ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\DataDictionary"/>
     </Resource>

     <Resource Name="StrPreliminaryLayoutIDSchema" Description="Structure Preliminary Layout ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\StructurePreliminaryLayout\DataDictionary"/>
     </Resource>

     <Resource Name="StrFunctionalDesignIDSchema" Description="Structure Functional Design ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\StructureFunctionalDesign\DataDictionary"/>
     </Resource>

     <Resource Name="CompAccessIDSchema" Description="Compartment Access ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\CompartmentAccess\DataDictionary"/>
     </Resource>

     <Resource Name="ElectricalIDSchema" Description="Electrical ID Schema Directory">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\Electrical\DataDictionary"/>
     </Resource>

  <!-- ************** USER DICTIONARY RESOURCES ************** -->

     <Resource Name="EquipmentUserDictionary" Description="Equipment User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATEquipmentSample.CATfct"/>
     </Resource>

     <Resource Name="HVACUserDictionary" Description="HVAC User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATHVACSample.CATfct"/>
     </Resource>

     <Resource Name="InstrumentUserDictionary" Description="Instrument User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATInstrumentSample.CATfct"/>
     </Resource>

     <Resource Name="PipingUserDictionary" Description="Piping User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATPipingSample.CATfct"/>
     </Resource>

     <Resource Name="TubingUserDictionary" Description="Tubing User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATTubingSample.CATfct"/>
     </Resource>

     <Resource Name="WaveguideUserDictionary" Description="Waveguide User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATWaveguideSample.CATfct"/>
     </Resource>

     <Resource Name="MultiDisciplineUserDictionary" Description="MultiDiscipline User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATMultiDisciplineSample.CATfct"/>
     </Resource>

     <Resource Name="StrPreLayoutUserDictionary" Description="Structure Preliminary Layout User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATStrPreliminaryLayoutSample.CATfct"/>
     </Resource>

     <Resource Name="StrFuncDesignUserDictionary" Description="Structure Functional Design User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATStructureFunctionalDesignSample.CATfct"/>
     </Resource>

     <Resource Name="CompAccessUserDictionary" Description="Compartment Access User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATCompAccessSample.CATfct"/>
     </Resource>

     <Resource Name="ElectricalUserDictionary" Description="Electrical User Dictionary">
           <ID  Type="Misc" Driver="File" Location="CATElectricalSample.CATfct"/>
     </Resource>


  <!-- ************** COMPUTED ATTRIBUTE RESOURCES ************** -->

     <Resource Name="EquipmentComputedAttributes" Description="Equipment list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\EquipmentComputedAttributes.txt"/>
     </Resource>

     <Resource Name="PipingComputedAttributes" Description="Piping list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\PipingComputedAttributes.txt"/>
     </Resource>

     <Resource Name="InstrumentComputedAttributes" Description="Instrument list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\InstrumentComputedAttributes.txt"/>
     </Resource>

     <Resource Name="HVACComputedAttributes" Description="HVAC list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\HVACComputedAttributes.txt"/>
     </Resource>

     <Resource Name="TubingComputedAttributes" Description="Tubing list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\TubingComputedAttributes.txt"/>
     </Resource>

     <Resource Name="WaveguideComputedAttributes" Description="Waveguide list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\WaveguideComputedAttributes.txt"/>
     </Resource>

     <Resource Name="RacewayComputedAttributes" Description="Raceway list of computed attribute names">
           <ID  Type="Path" Driver="File" Location="\startup\EquipmentAndSystems\MultiDiscipline\SampleData\RacewayComputedAttributes.txt"/>
     </Resource>

     <Resource Name="ConduitComputedAttributes" Description="Conduit list of computed attribute names">
