<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE MappingClasses[
<!ELEMENT MappingClasses (PanelSystem+)>
<!ELEMENT PanelSystem (PlateSystem,StiffenerSystemFirstDirection,StiffenerSystemSecondDirection)>
<!ATTLIST PanelSystem name CDATA #REQUIRED>
<!ELEMENT PlateSystem (#PCDATA)>
<!ELEMENT StiffenerSystemFirstDirection (#PCDATA)>
<!ELEMENT StiffenerSystemSecondDirection (#PCDATA)>
]>

<MappingClasses>
  <PanelSystem name='CATStrPanelSystem'>
    <PlateSystem>CATStrPlateSystem</PlateSystem>
    <StiffenerSystemFirstDirection>CATStrStiffenerSystem</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection></StiffenerSystemSecondDirection>
  </PanelSystem>
  <PanelSystem name='XXXDeckPanelSyst'>
    <PlateSystem>XXXDeckPlateSyst</PlateSystem>
    <StiffenerSystemFirstDirection>XXXLongStiffSyst</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection>XXXTransStiffSyst</StiffenerSystemSecondDirection>
  </PanelSystem>
  <PanelSystem name='XXXWDeckPanelSyst'>
    <PlateSystem>XXXWDeckPlateSyst</PlateSystem>
    <StiffenerSystemFirstDirection>XXXLongStiffSyst</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection>XXXTransStiffSyst</StiffenerSystemSecondDirection>
  </PanelSystem>
  <PanelSystem name='XXXTransPanelSyst'>
    <PlateSystem>XXXTransPlateSyst</PlateSystem>
    <StiffenerSystemFirstDirection>XXXLongStiffSyst</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection>XXXTransStiffSyst</StiffenerSystemSecondDirection>
  </PanelSystem>
  <PanelSystem name='XXXLongPanelSyst'>
    <PlateSystem>XXXLongPlateSyst</PlateSystem>
    <StiffenerSystemFirstDirection>XXXLongStiffSyst</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection>XXXTransStiffSyst</StiffenerSystemSecondDirection>
  </PanelSystem>
  <PanelSystem name='XXXUnspecPanelSyst'>
    <PlateSystem>XXXUnspecPlateSyst</PlateSystem>
    <StiffenerSystemFirstDirection>XXXUnspecStiffSyst</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection></StiffenerSystemSecondDirection>
  </PanelSystem>
  <PanelSystem name='XXXExtAppPanelSyst'>
    <PlateSystem>XXXExtAppPlateSyst</PlateSystem>
    <StiffenerSystemFirstDirection>XXXExtAppStiffSyst</StiffenerSystemFirstDirection>
    <StiffenerSystemSecondDirection></StiffenerSystemSecondDirection>
  </PanelSystem>
</MappingClasses>

