=== TZP001/test/B21/win_b64/code/dictionary/ReportDefinition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Report (Report_Body, Report_Support*)>
<!ELEMENT Report_Body (Report_Title?, Report_StyleSheet?, Report_Attribute+)>
<!ELEMENT Report_Support (Report_Query*, Report_Package*, Report_Attribute_Program_Library*, Report_V5_Environment*)>
<!--====================================================================  -->
<!-- Report_Title                        ==============================================  -->
<!--====================================================================  -->
<!-- it could be integes for (column,row) specification as in EXCEL application                   -->
<!ELEMENT Report_Title EMPTY>
<!ATTLIST Report_Title
	Title CDATA #REQUIRED
>
<!--====================================================================  -->
<!-- Report_StyleSheet    ==============================================  -->
<!--====================================================================  -->
<!--                                                                      -->
<!ELEMENT Report_StyleSheet EMPTY>
<!ATTLIST Report_StyleSheet
	Path CDATA #REQUIRED
>
<!--====================================================================  -->
<!-- Report_Attribute                 ==============================================  -->
<!--====================================================================  -->
<!-- The attribute columns is ordered according to the order of the attribute entries in         -->
<!-- the XML                                                                                                                            -->
<!ELEMENT Report_Attribute EMPTY>
<!ATTLIST Report_Attribute
	Field_Name CDATA #REQUIRED
	Field_Type (attribute | program | system | expr_str | expr_int | expr_dbl) #REQUIRED
	Field_Label CDATA #REQUIRED
	Field_Operation (group_by | sum | both | none) #IMPLIED
	Field_Sort (yes | no) #IMPLIED
>
<!--====================================================================  -->
<!-- Report_Query    ======================================================  -->
<!--====================================================================  -->
<!ELEMENT Report_Query EMPTY>
<!ATTLIST Report_Query
	Query_Name CDATA #IMPLIED
	Query_Text CDATA #IMPLIED
>
<!--====================================================================  -->
<!-- Report_Packages  - user program packages  ===============================  -->
<!--====================================================================  -->
<!ELEMENT Report_Package EMPTY>
<!ATTLIST Report_Package
	Package_Name CDATA #IMPLIED
>
<!--====================================================================  -->
<!-- Report_Program_Library ===============================================  -->
<!--====================================================================  -->
<!ELEMENT Report_Attribute_Program_Library EMPTY>
<!ATTLIST Report_Attribute_Program_Library
	Library_Name CDATA #REQUIRED
>
<!--====================================================================  -->
<!-- Report_V5_Environment  ===============================================  -->
<!--====================================================================  -->
<!-- Object_Type is the type associated with the above attributes                                       -->
<!ELEMENT Report_V5_Environment EMPTY>
<!ATTLIST Report_V5_Environment
	Object_Type CDATA #REQUIRED
>

=== TZP001/test/B21/win_b64/startup/EquipmentAndSystems/Tubing/SampleData/TubeLineList.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE Report SYSTEM "ReportDefinition.dtd">
<Report>
  <Report_Body>
    <Report_Title Title = "Tubing Line List"/>
    <Report_StyleSheet Path = "C:\Documents and Settings\IPA\Desktop\"/>
    <Report_Attribute Field_Name = "Name                   " Field_Type = "attribute" Field_Label = "Name                    " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "ClassName" Field_Type = "attribute" Field_Label = "Class Name" Field_Operation = "none"/>
    <Report_Attribute Field_Name = "NominalSize            " Field_Type = "attribute" Field_Label = "Nominal Size            " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "TubeSpecification      " Field_Type = "attribute" Field_Label = "Tube Specification      " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "CommodityType          " Field_Type = "attribute" Field_Label = "Commodity Type          " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "DesignTemperature      " Field_Type = "attribute" Field_Label = "Design Temperature      " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "DesignPressure         " Field_Type = "attribute" Field_Label = "Design Pressure         " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "InsulationSpecification" Field_Type = "attribute" Field_Label = "Insulation Specification" Field_Operation = "none"/>
    <Report_Attribute Field_Name = "InsulationThickness    " Field_Type = "attribute" Field_Label = "Insulation Thickness    " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "FromToTable            " Field_Type = "attribute" Field_Label = "From To Table           " Field_Operation = "none"/>
  </Report_Body>
  <Report_Support>
    <Report_Query Query_Name = "All Tubing Lines" Query_Text = "'Tubing Design'.'Tubing Line',all"/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingLine"/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingPartFunc"/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
    <Report_V5_Environment Object_Type = "TubingLine    "/>
  </Report_Support>
</Report>

=== TZP001/test/B21/win_b64/startup/EquipmentAndSystems/Piping/SampleData/PipingCutLengthList.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE Report SYSTEM "ReportDefinition.dtd">
<Report>
  <Report_Body>
    <Report_Title Title = "Pipe Cut Length Report"/>
    <Report_StyleSheet Path = "C:\Documents and Settings\IPA\Desktop\"/>
    <Report_Attribute Field_Name = "Name                " Field_Sort = "yes" Field_Type = "attribute" Field_Label = "Name                   " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "PartNumber          " Field_Type = "attribute" Field_Label = "Part Number            " Field_Operation = "group_by"/>
    <Report_Attribute Field_Name = "PartName" Field_Type = "attribute" Field_Label = "Part Name" Field_Operation = "none"/>
    <Report_Attribute Field_Name = "NominalSize         " Field_Type = "attribute" Field_Label = "Nominal Size           " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "MaterialCategory    " Field_Type = "attribute" Field_Label = "Material Category      " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "MaterialCode        " Field_Type = "attribute" Field_Label = "Material Code          " Field_Operation = "none"/>
    <Report_Attribute Field_Name = "ParentPipingLineName" Field_Type = "attribute" Field_Label = "Parent Piping Line Name" Field_Operation = "none"/>
    <Report_Attribute Field_Name = "PipeLength          " Field_Type = "attribute" Field_Label = "Pipe Length            " Field_Operation = "sum"/>
    <Report_Attribute Field_Name = "_Quantity_" Field_Type = "system" Field_Label = "_Quantity_             " Field_Operation = "none"/>
  </Report_Body>
  <Report_Support>
    <Report_Query Query_Name = "All Piping Pipes 17" Query_Text = "'Piping Design'.Pipes,all"/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "PipingPipe"/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "PipingPipe      "/>
    <Report_V5_Environment Object_Type = "AnalysisSolution"/>
  </Report_Support>
</Report>
